// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-chUfFjVW4aYa1eJnMm0HOxklIir2pE',
    appId: '1:1072995791359:web:91139c85ad8962c488b7ca',
    messagingSenderId: '1072995791359',
    projectId: 'fir-flutter-codelab-2287b',
    authDomain: 'fir-flutter-codelab-2287b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2287b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPO8JxFMTv4rlbQuMm1PG383U9OGyokho',
    appId: '1:1072995791359:android:e8f981266e2fa9e088b7ca',
    messagingSenderId: '1072995791359',
    projectId: 'fir-flutter-codelab-2287b',
    storageBucket: 'fir-flutter-codelab-2287b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94zk9v18AWWc4abYLPrXzsvIpi1CqjHw',
    appId: '1:1072995791359:ios:e268e866c280de2888b7ca',
    messagingSenderId: '1072995791359',
    projectId: 'fir-flutter-codelab-2287b',
    storageBucket: 'fir-flutter-codelab-2287b.appspot.com',
    iosClientId: '1072995791359-48pjnvn5alir68rr9b833d7hnrdhlnus.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB94zk9v18AWWc4abYLPrXzsvIpi1CqjHw',
    appId: '1:1072995791359:ios:e268e866c280de2888b7ca',
    messagingSenderId: '1072995791359',
    projectId: 'fir-flutter-codelab-2287b',
    storageBucket: 'fir-flutter-codelab-2287b.appspot.com',
    iosClientId: '1072995791359-48pjnvn5alir68rr9b833d7hnrdhlnus.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );
}
